### ISSUE TITLE
failed to fill whole buffer

### ISSUE THREAD

**Issue by boborjan2** [bet4it/udbserver#17]
Hi, what frontends are known to work?

I get the following error using iato:

"Debugger connected from 127.0.0.1:59796
thread '<unnamed>' panicked at src/lib.rs:42:87:
Failed to start udbserver: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5"

The full output:
 RUST_BACKTRACE=1 RUST_BACKTRACE=full bin/PortExEmuDebug -g -u -o dump -d bin/stub_mods -v 4 test/upx_pafish/pafish_upx.bin dump/out.json
Waiting for a GDB connection on "0.0.0.0:1234"...
Debugger connected from 127.0.0.1:59096
thread '<unnamed>' panicked at src/lib.rs:42:87:
Failed to start udbserver: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
stack backtrace:
   0:     0x55cf8e49744b - std::backtrace_rs::backtrace::libunwind::trace::h59b05d333ef250f9
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55cf8e49744b - std::backtrace_rs::backtrace::trace_unsynchronized::hbad10f6c65416841
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55cf8e49744b - std::sys_common::backtrace::_print_fmt::hda4a67a10610ef78
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55cf8e49744b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he8d8a3d249a948a2
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55cf8e4f0860 - core::fmt::rt::Argument::fmt::h507ca91fbb1ef494
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/fmt/rt.rs:142:9
   5:     0x55cf8e4f0860 - core::fmt::write::h4d5f6025aa566322
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/fmt/mod.rs:1120:17
   6:     0x55cf8e48399d - std::io::Write::write_fmt::h1b572fe055a121e6
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/io/mod.rs:1762:15
   7:     0x55cf8e497234 - std::sys_common::backtrace::_print::hcaa91a137f39fd45
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55cf8e497234 - std::sys_common::backtrace::print::hdf91ee03271e5d94
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55cf8e4d454a - std::panicking::default_hook::{{closure}}::h59f1f95e0a9a0472
  10:     0x55cf8e4d41ed - std::panicking::default_hook::h731f67f92b204ede
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:292:9
  11:     0x55cf8e4d4aa8 - std::panicking::rust_panic_with_hook::hbcae08ba0ccf4c11
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:779:13
  12:     0x55cf8e4978ee - std::panicking::begin_panic_handler::{{closure}}::h9083954869cd1afa
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:657:13
  13:     0x55cf8e497666 - std::sys_common::backtrace::__rust_end_short_backtrace::hb8caade51576a0bc
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55cf8e4d47d2 - rust_begin_unwind
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:645:5
  15:     0x55cf8e435ea5 - core::panicking::panic_fmt::hef0307862026e6f9
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/panicking.rs:72:14
  16:     0x55cf8e436743 - core::result::unwrap_failed::h8393ef8d489acb45
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/result.rs:1653:5
  17:     0x55cf8e50c87d - unicorn_engine::ffi::code_hook_proxy::hef624a9c69bde2d4
  18:     0x55cf8e5269cb - helper_uc_tracecode
                               at /home/v/work/unicorn-2.x/uc.c:1785:14
  19:     0x7f66ab547135 - <unknown>
fatal runtime error: failed to initiate panic, error 5
Aborted

udbserver/unicorn running  in wsl, frontend on win 11.

Thanks, Viktor

**Comment by boborjan2** [comment]
I see that I need to use gdb-multiarch. I confirm I can connect to udbserver with gdb-multiarch.
Would you give me a hint what to modify so that it runs with non-multiarch gdb client?

Thanks in advance
Viktor

**Comment by boborjan2** [comment]
OK, I got it. Thx for your work. 

Cheers Viktor
